// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eixbwzqaxgdbnjuzpumk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpeGJ3enFheGdkYm5qdXpwdW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0Mzc2NTMsImV4cCI6MjA1ODAxMzY1M30.vHM_gWRE70AhFyHveCwHtEhtI9Cig3G8Ahrv9OKMGAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);